### ISSUE TITLE
tRNA, rRNA (and apparently, ncRNA) do not have a locus page

### ISSUE THREAD

**Issue by bkm** [metagenlab/chlamdb#2]
This is something that will need to be added.

**Comment by tpillone** [comment]
Only protein coding genes are annotated and compared because all comparisons/annotations rely on amino acid sequences. 
We could start by simply display the annotation of ncRNAs in the interface. 
If we want to have comparative data, we need to expand the annotation pipeline to extract RNAs, cluster them into orthologous groups and build a phylogeny for each group.

**Comment by bkm** [comment]
For now, the interface display basic information on the r/t/tmRNA instead of crashing.

**Comment by bkm** [comment]
This has been fixed.
